version: "3.8"

services:
  deconz:
    container_name: deconz
    image: marthoc/deconz:stable
    restart: always
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_MODE=0
      - DECONZ_WS_PORT=8443
      - DECONZ_WEB_PORT=8080
      - TZ=Europe/London
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    volumes:
      - ~/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ
    restart: unless-stopped

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: always
    environment:
      - TZ=Europe/London
    volumes:
      - ~/docker/hassio:/config
    network_mode: host # 8123
