services:
  deconz:
    image: marthoc/deconz:stable
    container_name: deconz
    restart: always
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_MODE=0
      - DECONZ_WS_PORT=8443
      - DECONZ_WEB_PORT=8080
      - TZ=Europe/London
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ~/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ
    network_mode: host

  hass:
    image: homeassistant/home-assistant:stable
    container_name: hass
    restart: always
    environment:
      - TZ=Europe/London
    volumes:
      - ~/docker/hassio:/config
    network_mode: host # 8123

  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    environment:
      - USERID=1000
      - GROUPID=1000
      - VETO=yes
    volumes:
      - ~/samba:/c
    network_mode: host
    healthcheck:
      disable: true
    command: -p -n -r -u "c;c" -u "Sarah;c" -s "c;/c;no;no;no;c,Sarah;none;c,Sarah" -W -S

  dl:
    image: hurlenko/aria2-ariang
    container_name: dl
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN=0.0.0.0:80
      - ARIA2RPCPORT=80
    volumes:
      - ~/docker/aria2/conf/:/aria2/conf/
      - ~/samba/:/aria2/data/
    network_mode: host
