all:
  children:
    laptop:
      hosts:
        oo:
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: c
          ansible_connection: ssh
          ansible_port: 23
          ansible_host: 192.168.1.5
